const bagsthree = [
    {
        id: 1,
        title: "POCHETTE MÉTIS",
        code: "M46279",
        price: "€2.210,00",
        image: "https://it.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-pochette-m%C3%A9tis-east-west-tela-monogram-borse-da-donna--M46279_PM2_Front%20view.png?wid=2048&hei=2048",
        category: "Borsa a spalla",
        a: "https://it.louisvuitton.com/ita-it/prodotti/neverfull-mm-monogram-007653/M41177",
        },
    {
        id: 2,
        title: "SPEEDY BANDOULIÈRE",
        code: "M20973",
        price: "€1.700,00",
        image: "https://it.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-speedy-bandouli%C3%A8re-25-autres-toiles-monogram-borse-da-donna--M20973_PM2_Front%20view.png?wid=2048&hei=2048",
        category: "Borsa a spalla",
        a: "https://it.louisvuitton.com/ita-it/prodotti/neverfull-mm-monogram-007653/M41177",
    },
    {
        id: 3,
        title: "NEVERFULL MM",
        code: "M45685",
        price: "€2.060,00",
        image: "https://it.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-neverfull-mm-pelle-monogram-empreinte-borse-da-donna--M45685_PM2_Front%20view.png?wid=2048&hei=2048",
        category: "Borsa a spalla",
        a: "https://it.louisvuitton.com/ita-it/prodotti/neverfull-mm-monogram-007653/M41177",
    },
    {
        id: 4,
        title: "POCHETTE FÉLICIE",
        code: "M81545",
        price: "€1.220,00",
        image: "https://it.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-pochette-f%C3%A9licie-tela-monogram-portafogli-e-piccola-pelletteria--M81545_PM2_Front%20view.png?wid=2048&hei=2048",
        category: "Borsa a spalla",
        a: "https://it.louisvuitton.com/ita-it/prodotti/neverfull-mm-monogram-007653/M41177",
    },
    {
        id: 5,
        title: "BORSA DIANE",
        code: "M46317",
        price: "€2.320,00",
        image: "https://it.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-borsa-diane-tela-monogram-borse-da-donna--M46317_PM2_Front%20view.png?wid=2048&hei=2048",
        category: "Borsa a spalla",
        a: "https://it.louisvuitton.com/ita-it/prodotti/neverfull-mm-monogram-007653/M41177",
    },
    {
        id: 6, 
        title: "MINI POCHETTE ACCESSOIRES",
        code: "M81633",
        price: "€620,00",
        image: "https://it.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-mini-pochette-accessoires-tela-monogram-portafogli-e-piccola-pelletteria--M81633_PM2_Front%20view.png?wid=2048&hei=2048",
        category: "Borsa a mano",
        a: "https://it.louisvuitton.com/ita-it/prodotti/neverfull-mm-monogram-007653/M41177",
    },
    {
        id: 7,
        title: "PORTAFOGLIO SARAH",
        code: "N63551",
        price: "€595,00",
        image: "https://it.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-portafoglio-sarah-tela-damier-%C3%A9b%C3%A8ne-portafogli-e-piccola-pelletteria--N63551_PM2_Front%20view.png?wid=1240&hei=1240",
        category: "Portafoglio",
    },
    {
        id: 8,
        title: "ALMA BB",
        code: "M53152",
        price: "€1.340,00",
        image: "https://it.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-alma-bb-tela-monogram-borse-da-donna--M53152_PM1_Back%20view.png?wid=2048&hei=2048",
        category: "Borsa a spalla",
    },
    ];
        
const bags = [
    {
        id: 1,
        title: "NEVERFULL MM",
        code: "M41177",
        price: "€1.500,00",
        image: "https://it.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-neverfull-mm-tela-monogram-borse-da-donna--M41177_PM2_Front%20view.png?wid=2048&hei=2048",
        material: "Tela monogram",
        category: "Borsa a mano",
        description: "La borsa Neverfull MM unisce dettagli iconici a un design senza tempo. Il capiente modello, realizzato in tela Monogram con finiture in vacchetta, presenta laccetti laterali e comodi manici, che consentono di portarlo a spalla o al braccio. L'elegante accessorio è completato da una fodera colorata e da una pochette amovibile, che funge sia da tasca che da piccola borsa.",
    },
    {
        id: 2,
        title: "SPEEDY 30",
        code: "M41108",
        price: "€1.180,00",
        image: "https://it.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-speedy-30-tela-monogram-borse-da-donna--M41108_PM2_Front%20view.png?wid=2048&hei=2048",
        material: "Tela monogram",
        category: "Borsa a mano",
        description: "La borsa Speedy 30, realizzata nell'iconica tela Monogram, è elegante e compatta, perfetta per la città. L'esclusivo modello, lanciato nel 1930 come Express, rievoca l'intramontabile icona della Maison con un tocco di sofisticata contemporaneità. L'accessorio, dalle linee inconfondibili, è completato da due manici in pelle e un lucchetto con firma Louis Vuitton.",
    },
    {
        id: 3,
        title: "POCHETTE MÉTIS",
        code: "M44875",
        price: "€1.960,00",
        image: "https://it.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-pochette-m%C3%A9tis-tela-monogram-borse-da-donna--M44875_PM2_Front%20view.png?wid=2048&hei=2048",
        material: "Tela monogram",
        category: "Borsa a mano",
        description: "Pratica nel design, la Pochette Métis è l'espressione stessa dell'eleganza. In morbida tela Monogram, questo modello compatto di borsetta si contraddistingue al suo interno per una miriade di utili tasche e scomparti.",
    },
    {
        id: 4,
        title: "MULTI POCHETTE",
        code: "M44813",
        price: "€1.960,00",
        image: "https://it.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-multi-pochette-accessoires-tela-monogram-borse-da-donna--M44813_PM2_Front%20view.png?wid=2048&hei=2048",
        material: "Tela monogram",
        category: "Borsa a spalla",
        description: "La multi pochette Accessoires è un omaggio a tre icone della Maison: l'omonimo accessorio, la sua versione mini e il portamonete rotondo. Il modello, realizzato nell'emblematica tela di LV, presenta svariate tasche e scomparti. La catenella dorata e la tracolla in jacquard consentono di portare l'accessorio in diversi modi.",
    },
];


const bagstwo = [
{
    id: 1,
    title: "BORSA NÉONOÉ",
    code: "N40198",
    price: "€1.550,00",
    image:"https://it.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-borsa-n%C3%A9ono%C3%A9-tela-damier-%C3%A9b%C3%A8ne-borse-da-donna--N40198_PM2_Front%20view.png?wid=2048&hei=2048",
    material: "Tela damier ébène",
    category: "Borsa a spalla",
    description: "La borsa NéoNoé, realizzata in tela Damier Ébène, è impreziosita da coulisse e fodera coordinate. L'accessorio è comodo, leggero ed è completato da una tracolla regolabile, che lo rende estremamente versatile. L'interno è dotato di una tasca con zip, perfetta per tenere al sicuro gli oggetti di valore.",
},
{
    id: 2,
    title: "BORSA PETITE MALLE",
    code: "M45953",
    price: "€4.350,00",
    image: "https://it.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-borsa-petite-malle-tela-monogram-borse-da-donna--M45943_PM2_Front%20view.png?wid=2048&hei=2048",
    material: "Tela monogram",
    category: "Borsa a spalla",
    description: "La borsa Petite Malle riproduce in versione mini i classici bauli da viaggio di Louis Vuitton. L'originale modello, è ricco di dettagli distintivi, dall'iconica tela Monogram alla chiusura dorata, alla fodera in pelle di agnello con emblematico motivo della Maison. Può essere portato come pochette oppure utilizzando la tracolla regolabile.",
},
{
    id: 3,
    title: "BORSA LOOP HOBO",
    code: "M46311",
    price: "€2.110,00",
    image: "https://it.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-borsa-loop-hobo-tela-monogram-borse-da-donna--M46311_PM2_Front%20view.png?wid=2048&hei=2048",
    material: "Tela Monogram Reverse",
    category: "Borsa a spalla",
    description: "La borsa Loop Hobo, capiente e compatta al contempo, abbina con eleganza tela Monogram alla sua versione Reverse. L'esclusivo design a mezzaluna è impreziosito dagli originali angoli in pelle. La catenella insieme alla tracolla regolabile, entrambe amovibili, consentono di portare l'accessorio di tendenza con grande versatilità.",
},
{
    id: 4,
    title: "BORSA CAPUCINES BB",
    code: "M20709", 
    price: "€5.250,00",
    image: "https://it.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-borsa-capucines-bb-capucines-borse-da-donna--M20709_PM2_Front%20view.png?wid=2048&hei=2048",
    material: "Pelle Taurillon",
    category: "Borsa a mano",
    description: "La borsa Capucines BB è proposta in una raffinata versione con iniziali LV e staffe del manico in smalto. L'iconico modello, in pelle Taurillon, è rifinito dalla fodera colorata in twill, impreziosita dalla stampa con fiori Monogram. I bordi tinti a contrasto aggiungono un tocco di sofisticata eleganza.",
},
];


export {bags};
export {bagstwo};
export {bagsthree};